edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_macro_definitions = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = true
where_single_line = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
normalize_comments = true
normalize_doc_attributes = true
format_doc_comments = true
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []

